### ISSUE TITLE
Support for firestick control

### ISSUE THREAD

**Issue by hudsonbrendon** [dimagoltsman/generic-remote-control-card#15]
is there the possibility of adding firestick control support? You can control it via ADB too.

![fire](https://user-images.githubusercontent.com/5201888/125863602-318358af-e77b-4251-968c-0eab9bbe1537.jpg)

**Comment by dimagoltsman** [comment]
Hi,
the point of this repo is that its very easy to contribute.
all remotes ware contributed except the first one that i created, you can copy one of them and just make the adjustments :)

**Comment by richsimpson** [comment]
@hudsonbrendon If you are still around, I have added one
