### ISSUE TITLE
card not visible - config check failed

### ISSUE THREAD

**Issue by wube1** [dimagoltsman/generic-remote-control-card#16]
Hi i have a problem with this card.
What i did:
1. installed card from HACS (version 0.2.3)
2. Added:
`resources:
  - url: /hacsfiles/generic-remote-control-card/generic-remote-control-card.js
    type: module`
to the config
3. Restarted HA
4. When checking configuration i get:
-  Component error: resources - Integration 'resources' not found.
5. I even checked if still is not in /config/www/community/generic-remote-control-card - checking configuration throws the same error.
6. The info before install says:
- When installed, this will be located in '/config/www/community/generic-remote-control-card'

Can you tell me what is wrong?

**Comment by wube1** [comment]
Actually it is installed in /config/www/community/generic-remote-control-card/generic-remote-control-card.js
but no matter what i put in resources i get:
Component error: resources - Integration 'resources' not found.

**Comment by dimagoltsman** [comment]
you    should not add `resources:` to the configuration.yaml, its the resources in the HA config

**Comment by wube1** [comment]
Can you let me know where exactly i should look?
![image](https://user-images.githubusercontent.com/35063100/132985658-107a2371-3285-4abe-a4bf-b31dd5ae8e91.png)

Nevermind i found the place but i must have done something wrong cause it's still not working ... i will check newer version of HA.. maybe that's why.
Thanks for all the help.
