### ISSUE TITLE
No 'remote' domain entities exposed for the LG tv

### ISSUE THREAD

**Issue by DennisOtt-git-hub** [dimagoltsman/generic-remote-control-card#17]
### LG Integration Question

Your LG examples show 'remote' service calls to entities in the 'remote' domain.  I have an LG smart tv that uses the remote control in your lg-new example but no integration I can find for the LG tv exposes a 'remote' entity (remote.living_room_tv).  How did this entity get defined in your system?

**Comment by wube1** [comment]
Hey DennisOtt-git-hub, how did you get the card to be addable? For me the card shows in HACS but i can't add to dashboard. I raised the issue which is open but so far no response from anyone.  Would appreciate the tip or two. Thanks.

**Comment by DennisOtt-git-hub** [comment]
Once instaled I just added the example code to a to the ui-lovelace.yaml file.  The image of the remote specified is included in the HACS directory (www/community/generic-remote-control-card/remotes.  The ui code has a call to the remote you desire.  

here is the code I used in my yaml.  



#  *******************************************************************************
  - title: Test LG Remote Remote Controls
#    visible: false
    path: lg_remote_control

    buttons:
      back:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_wifi
          command: >-
            b64:JgBgAAABJZEVEBITERMTEhMRExITEhISEjYUNhI3EzYTNhM1ExISNxQQFBETEhE4ExETEhM2EhISNxM2EzYTEhI3EzUUERM2EwAFOgABJ0gSAAwPAAEkSRMADA4AASVJEgANBQAAAAAAAAAA
      bottom:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKZIUERMSEhIUERUQFBEUERMSEzYUNhM2FTQUNhM2FBAUNhQ1FTQVNRQRFDUUERUQExITEhQRFBAVNBURFDUVNBU1FAAFTQABKUgVAA0FAAAAAAAAAAA=
      button0:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_wifi
          command: >-
            b64:JgBQAAABKpITERUQFRAUERQRFBETEhMRFTUUNRU0FTUTNhU0FRAVNRMSFBAVEBQRExIUERQRExEVNBU1FDUVNBU1FDUVNRQ1FAAFTgABKUgWAA0FAAAAAAAAAAA=
      button1:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_wifi
          command: >-
            b64:JgBQAAABKJIVEBUSEhISEhQRFBEUEBUQFjQUNRU0FDYUNRQ2FBETNhQ1FBEUERQRExETEhUQFBEUERQ1EzYVNRQ1FTQVNRQ1FQAFTQABKUgUAA0FAAAAAAAAAAA=
      button2:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_lan
          command: >-
            b64:JgBQAAABKZIWDxQRFBEUERQRExEVEBQSEzYSNxQ2EzYSNxQ2ExEUNRUQFTUUERMRFBEVEBQRFBETNhMSFTQVNRQ1FTUTNhQ1FQAFTQABKUgTAA0FAAAAAAAAAAA=
      button3:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKpITERUQFRAUEhMRFBEUERQQFTUUNRQ1FTUUNRU0FRAVNRQ1FTQVERMRExIVEBQQFRAVERQREzYUNRM3EjcTNhQ2EwAFTgABKUgVAA0FAAAAAAAAAAA=
      button4:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKZIUERQRFBEUEBUQFRETERQRFDUUNhQ1FTQVNRQ1FBEUNhMRFBEUNRUQExIUERQRFBEUNRM3ExEUNRU1FDUUNRU1FAAFTQABKkcVAA0FAAAAAAAAAAA=
      button5:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBUAAABKZIVEBITFBAVERQRExEUERQREzYUNhM2FDUUNhM2FQ8VNRQ1Fg8UNhQRExEVEBQRFRAUERQ1FBEUNRU1FDUVNBU1FQAFTAABKkcUAAFpCQANBQAAAAA=
      button6:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKpITEhMRFBEWDxMRFREVEBMRFDUVNRQ1FTQWNBQ1Fg8WMxYQEzYSNxQRFBEVEBQRExEUNRURFBETNhM2FDYTNhU0FAAFTgABJ0kVAA0FAAAAAAAAAAA=
      button7:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABJ5MWEBQRFBETERQRFRAUERQRFDUTNhU1FDUVNBU1ExITNhQ2EzUVNRQRFBETEhQRFBAVEBYPFRATNhM2FDYUNRQ1FQAFTgABKEgUAA0FAAAAAAAAAAA=
      button8:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABJ5MVEBURExEUERQRFQ8VEBUQFDYUNRU0FDYTNhQ2ExEUNRUQFRAVERM2ExEUERUQFBETNhQ1FTUUERQ1FTQVNRU0FQAFTQABKUgTAA0FAAAAAAAAAAA=
      button9:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKpIUERQQFRAWDxQRFBEUERQRFDUUNhM1FjQUNRQ1FBEUNhQ1FBEWDxQ2ExITERMSFBAVERM2FDUWDxQ2EjcUNRM3EgAFTwABKkcUAA0FAAAAAAAAAAA=
      buttonClear: null
      buttonEnter: null
      exit:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_lan
          command: >-
            b64:JgBYAAABJJMTEhISExEUERMSEhITERQREzYTNhM2EzYTNhM2ExEUNRMSExITNRQ2EjYUERM2ExETNhM3ERMTERMRFDYSEhM2EwAFOwABJ0cSAAwPAAElSBQADQU=
      info:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_lan
          command: >-
            b64:JgBQAAABKZMUEBUQExIUERMRFREUERMRFDUVNRQ1FDUVNRQ1FRAVNRQRExEUNRU1FBEUERMSFBAVMxc0FBEUERQ1FTUTNhQ2EwAFTgABKUcVAA0FAAAAAAAAAAA=
      left:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKpIVEBMRFRAVEBUQFBEUERQREjcUNhM2EzYUNhM2FBAVNRQ1FRAVEBQ2EzYTERYPFRAVERM2EjcUEBUREzYUNRQ2FAAFTQABKUgUAA0FAAAAAAAAAAA=
      menu:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_lan
          command: >-
            b64:JgBQAAABKJMUERQREhMSEhUQFRAUERUQFjMVNBU1FDUUNhQ1FBEUNRQRFBEUNRUQFDYTEhISFBEVNBU1FBETNhQQFTUTNhU0FQAFTgABKEgVAA0FAAAAAAAAAAA=
      mute:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgCgAJaSEQ8RDxIPEg8SMBIvEg8SDxIvETERMBAxEg8SDxIPEQ8SkhIPEg8SDxIPETASDxIPERARLxIwEi8SDxIPEjARMBIwERASDREQEjASAAdhlJMSDxEQERARDxIvEjASDxEPETESMBEwEjARDxAQEg8SDxKSEg8REBEPEg8SMBEQEQ8REBIwEi8SLxIPEg8SLxIwEi8SDxEQEg8RMBEADQUAAAAAAAAAAA==
      ok:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBUAAkACXEAASiTFRAUERQRFBETEhQRExEUERU1FDUUNRU1FDUUNRYPEzcTNhQQFjQTEhU0Fg8UERQRFBEVNBQRFDYSEhQ1FTQVNRQABU4AASlIFAANBQAAAAA=
      power:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKJIVERQRFBATEhQRFBAUEhQRFDUVNBU1EzYUNRQ2FBETNhQ2ExEUNRU1FBEUERQQFBEVEBU1ExEUERQ1FTUUNRQ1FQAFTQABKUgUAA0FAAAAAAAAAAA=
      right:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBQAAABKZIUERQRExIUERMRFBEVEBQREzYVNBU1FDUUNRU1FBETNhUQFBEUERQ1FTQVERMSExEUNRU1FDUUERUQFDUUNhM2FAAFTgABKEgVAA0FAAAAAAAAAAA=
      source:
        call: remote.send_command
        data:
          entity_id: remote.living_room_remote
          command: >-
            b64:JgBcAAwABPwAASmSFRAVEBQRFBEUERMSFBAUERU1FDUVNBU1FDUVNBUREzYUEBU1ExIUERM2FBAUERUREzYTERQ2FDUTEhQ1FTUUNRQABU0AASpIEwAMVgABKUgUAA0FAAAAAAAAAAAAAAAA
      top:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_lan
          command: >-
            b64:JgBQAAABKJIVERQRExIVDxQRFBEUERQREzYTNhU1FTQWMxU1FBETNhQRFDUUNRUQFTUUERMSFBAUNRURExIUNRQQFTUUNRM2FQAFTgABKEgVAA0FAAAAAAAAAAA=
      volmin:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_wifi
          command: >-
            b64:JgDgAJGUERAREA8RERERLxAyEBEQEBAyDjMRLxMwEBEOEg8RERAOlBMPEBEQEBEQEg8REBAQETIQMBEyEDAQEBIvEjEQMBIPDxIPEhEPETASAAdclJMSDhAREBEPEw8xEi8QERARDzEPMxEwETEQEBEREBASDhGTEg8RDxASEBEOERAQERARMBIwEi8RMhAQETEOMhExEBAREBARDxIPMhEAB1yWkRAQERAQERAREDESLxEREBARMBAxEDERMBEQEREOExAQEZIQERAQEhAQEQ0TEBEQEBExEDEQMBIwERARAA0FAAAAAAAAAAA=
      volplus:
        call: remote.send_command
        data:
          entity_id: media_player.familyroom_tv_lan
          command: >-
            b64:JgCgAJSSEg8QEBIPERAPMhEyDxERDxAxEDESLxAyEREPEREQEBAQlBARDxIQEBAREi8PMhEvEhAQMRExDzIREBARDhISDhAyEBEQEQ8REi8RAAdclJMRDxAREREPEREwEi8SEBARDzIQMhAwDzESEBARERAQEBKSEg8QEBAREREPMREyDjESDhIwETESLxEQEBEREBAQETAPERERERAQMRAADQUAAAAAAAAAAA==
      name: Hisense
      remote_template: lg_new
      style: |
        ha-card {
          font-size: 10px;
        }
        h1{
          text-align:left;
          margin-left: 50px;
        }

    name: Hisense
    remote_template: lg_new
    style: |
      ha-card {
        font-size: 10px;
      }
      h1{
        text-align:left;
        margin-left: 50px;
      }  
    type: 'custom:generic-remote-control-card'





The last section under  ‘name': references the remote template you wan to use in the remote directory. 

R/

**Comment by wube1** [comment]
Hey, ok so I want to add the samsung remote so i prepared the ir codes as per the example and added this piece of code to raw editor of the dashboard (saved ok after alligning the code). I restarted HA but I can't use or see the card nor remote:

`buttons:
back:
  call: remote.send_command
  data:
    entity_id: remote.rm_mini_3_remote
    command: b64:JgCMAI+UEjcTNxI3EhMSExITEhMRFBE4EjcSOBITExISEhQREhMTEhITERMSOBI3EhMSOBISEjgSNxM3ExITEhI3EhMSNxMABgCVkxM2EjgTNhMSExISFBETEhISOBI3EjgTEhMSEhISExMSEhMSEhITEjgSNxITEjgSEhI4EjcSOBMTEBMTNxEUEzYSAA0FAAAAAAAAAAAAAAAA
bottom:
  call: remote.send_command
  data:
    entity_id: remote.rm_mini_3_remote
    command: b64:JgCMAI+UEjcTNxM2ExISExITEhMSEhI4EjcSOBITEhMRExITEhMSNxMSEhMSExITEjcSOBISExISOBI3EjgSNxITEhMSNxMABgCUlBM2EjgSNxMSEhMSExISEhMSOBM2EjgSExISEhMSExITEjcUERITEhMSEhI4EjgSEhITEjgTNhI4EjcSExITEjcSAA0FAAAAAAAAAAAAAAAA
 zero:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM3EzcTEhMSEhMSEhM4EhITNxM3EzcTEhMSExITEhMSExITEhMSExITEhMSExITNxM3EzcTNxM3EzcSOBM3EgANBQ==
 one:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIJQTEhI4EjgSEhMSExITEhM3ExITNxM3EzcTEhMSExITEhM3ExITEhMSExITEhMSExITEhM3EjgSOBI4EzYTNxM3EwANBQ==
 two:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIJQSEhM3EzcTEhMSExITEhM3ExITNxM3EzcTEhMSExITEhMSEzcTEhMSExITEhMSEhMSNxMSEzcTNxM4EjcTNxM3EwANBQ==
 three:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM3EzcTEhMSExITEhM3ExITNxI3EzcTEhMSExITEhM3EzcTEhMSExITEhMSExITEhMSEzcTNxM3EzcTNxM3EwANBQ==
 four:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM4EjgSEhMSExITEhI4ExISOBI3EzcTEhMSExITEhMSExITNxMSExITEhMSExITNxM3ExITNxM3EzcTNxM3EwANBQ==
 five:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM3EjgSExITEhITEhM3ExITNxM3EzcTEhMSExITEhM3ExITNxMSExITEhMSExITEhM3ExITNxM3EjgSOBI4EgANBQ==
 six:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM3EzcTEhMSExITEhM3FBETNxM3EzcTEhITEhMSExITEjgSNxMSExITEhMSExITNxMSExITNxM3EzcTNxM3EwANBQ==
 seven:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM3EzcTEhMSExITEhM3ExITNxM3EzcSExITEhITEhM3EzcTNxMSExITEhMSExITEhMSExITNxM3EzcTNxM3EwANBQ==
 eight:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM3EjgSExITEhITEhM3ExITNxM3EzcTEhMSExITEhMSExITEhM3ExITEhMSExITNxM3EzcTEhI4EjgSNxM3EwANBQ==
 nine:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIpITEhM3EzcTEhMSExITEhM3ExITNxM3EzcTEhMSExITEhM3ExITEhM3EhMSEhMSExITEhM3EzcTEhM3EzcTNxM3EwANBQ==
 exit:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAI+TEzgRNxI4EhMSEhITExISExI3EjgSNxITEhMSExITEhMROBITETgSNxMSEjgTEhISEhMSOBISExITNxISEzcTNhMABgGSlRI4EjcSNxQRExMRExITEhMROBI3EjgSEhITEhMSFBETETgSExI3EjgSExI3EhQRExITETgSFBETETgTEhI3EjgSAA0FAAAAAAAAAAAAAAAA
 info:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBQAAABJpMTEhM3EjcTEhMSExETEhM3ExISNxM3EzcTERMSExITEhI3EzcSExISEjgTEhMREhMSExMREzcTNxMSEjcTNxM3EgAFYwABJ0oTAA0FAAAAAAAAAAA=
 left:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAI+UEzcSNxI4EhISExITEhMSExI3EzcSNxQREhMSExETEhMSOBISEjgSExISEjgTNxISEhMSOBMREjgSNxMSEhMSOBIABgCVkxM2EjgSNxITEhMTExETERMSOBI3EjgTEhMSERMSExITEjcTEhM3EhITEhI4EzYSExMSEzYSExI4EzYSExITEjcSAA0FAAAAAAAAAAAAAAAA
 menu:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAI6UEzcSNxM3EhMTEhISExISExI4EjcSOBISEhMSExITEhMSEhI4ExISNxM3EhITEhITEjgSEhI4ExISEhI4EjcTNxIABgCUlBI4EjcSOBITEhISExITEhMSNxI4EjcSExMSEhMSEhITERURNxMSEjgSNxITEhMSExI3ExISNxMSEhMSOBI3EjgSAA0FAAAAAAAAAAAAAAAA
 mute:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBQAAABIZMTEhITEhITExEUEhITNxM2EjgTNxI3EjgSOBM2EhMSEhMTEjcTEhITEhITEhIUETgSNxMSEjgTNxI3EjcUNxISEwAFHgABI0oSAA0FAAAAAAAAAAA=
 ok:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAI+UEzcSNxI4EhMSEhMSEhMSExI3EjgTNhMSEhMSExITExETEhITEhMSNxITEjgSNxITEjcTNxI4EhITNxITEhMSNxIABgCUlBM3EjcSOBMSEhMSEhITEhMSNxI4EjcTEhITEhMSExETEhMSExITEjcTEhI4EjcSExM2EzcSNxITEjgSExISEjgSAA0FAAAAAAAAAAAAAAAA
 power:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgAYAY2TEzcTNxM3ExITEhMSExITEhM3FDYTNxMSExITEhMSExISExI4EjgSExITEjcTNxM3EzcTEhMSEzcTNxMSExITEhMABeOTkxM3EzcTNxMSExITEhMSExITNxM3EzcSExITEhITEhMSExITNxM3ExITEhM3EzcTNxM3ExITEhM3EzcTEhMSExITAAXjk5MTNxQ3EjcTEhMSEhMSExISEzgSNxM3ExITEhMSExITEhMSEzcTNxMSExITNxM3EzcTNxMSExITNxM3EhMSExITEgAF45OTEzcTNxM3ExITEhMSExITEhM3EzcTNxMSExITEhMSExITEhM3EzcTEhMSEzcSOBM2EzcTEhMTEjcTNxMSExITEhMADQU=
 right:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAI+UEjcSOBI3EhMSExISExITEhI3EzcSOBISEhMSExITEhMSEhI4EhMSEhITEjgSNxITEjgSEhI4EjcSOBITEhITNxMABf+VkxI4EjcSOBMSEhISExITEhMSNxI4EzYTEhMSExISEhITEhMTNxISEhMSExI3EjgSExM2ExITNxI3EjgSEhITEjgSAA0FAAAAAAAAAAAAAAAA
 source:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBGAJOUEjgSOBI4EhMSExITEhMSExI4EjgSOBITEhMSExITEhMSOBITEhMSExITEhMSExITEhMSOBI4EjgSOBI4EjgSOBIADQUAAA==
 top:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAI+UEzcTNhI4ExETEhMSEhMSExI3EjgSNxMSEhMSExISEhMSExITERQSEhITEjgSNxITEjcSOBI3EzcSOBISEhMSOBMABf+UlBI3EjgSNxMSEhMSExITEhISOBI3EzcSExITEhISExITEhMSExISEhMSExI3EjgSExI3EzcSNxI4EzYTEhITEjcTAA0FAAAAAAAAAAAAAAAA
 volmin:
    call: remote.send_command
    data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBQAAABIpITEhIUERMUERITEhITNxI4EjcTNxI4EjcTNxM2EhQRExQ2EhIUERITExITEhITEjgRExI4EjcTNxI4EjcTNxMRFAAFGgABJ0kSAA0FAAAAAAAAAAA=
 volplus:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBQAAABIZMTEhITEhMSExITEhITNxI4EjcTNxI3EjgTNxI3EhMSExM3EhITNxITEjgSEhMSEjcTExI3ExISNxMSEjgTNxISEwAFGgABJ0oSAA0FAAAAAAAAAAA=
 channelup:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIZMTEhM3EzcTEhITEhITEhM3ExITNxM3EzcTEhMSExITEhMSExITEhMSEzcTEhMSExITNxM3EzcTNxMSEzcSOBI4EgANBQ==
 channeldown:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBIAAABIJMTEhM3EzcTEhMSExITEhM3ExITNxM3EzcSEhMSExITExISEzcTEhM3EzcTEhMSExITNxMSEzcTEhMSEzcTNxM3EwANBQ===
 guide:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAJSTEjcSNxI4EhISExITEhISExI3EjcSNxMSEhMSEhITEhMSNxI3EjcSNxMSEhMSNxITEhISExITEhISNxI3ExISNxIABfuTlBI3EjcSNxITEhMSEhITEhMROBI3EjcSExITERMSExISEjgROBI3EjcSExITETgSEhITEhMRExITEjcSNxITEjcSAA0FAAAAAAAAAAAAAAAA
 fastforward:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBGAJSVDzsQOhA6EBURFA8WERQSExA6EjgQOhAVEBUQFREUEBUQFREUEBUROREUEhMQOhAVEDoRORE5ERQRORE5EhMSOBEADQUAAA==
 rewind:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBGAJOUDzsPOxA6EBURFBAVEBYOFg87EDoQOhEUDxYPFg8WDxYQOhAVDzsQFQ8WEhMQOhAVEBURORAVETkRORE5ERQQOhEADQUAAA==
 play:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBGAJOUETkRORA7EBUQFRAVEBUQFQ87DzsPOw8WEBUQFRAVEBUPOxA6EDoRFBEUEBURORAVEBURFBEUEDoRORE5ERUPOw8ADQUAAA==
 pause:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgBGAJKVETkQOhA6EhMQFREUERQQFRA7DzsQOhAVEBUPFhAVDxYQFRE5EBUQOhAVERQROREUETkQFRE5ERQQOhA6EBUQOhAADQUAAA==
 lastch:
   call: remote.send_command
   data:
     entity_id: remote.rm_mini_3_remote
     command: b64:JgCMAJSTEzYTNhM3EhITEhMSEhITEhI3EzYTNhMSExISEhMSExISNxI3ExISEhI3EhMSExISEhMSExI3EjcSExE4EjcSNxIABfuUkhM3EjcTNhMSEhITEhMSEhITNhM3EjcTEhISExISEhMSEzYTNhMSExISNxMRExITEhISExITNhM2ExITNhM2EzcSAA0FAAAAAAAAAAAAAAAA
 name: Samsung
 remote_template: samsungtv
 style: |
  ha-card {
    font-size: 10px;
  }
  h1{
    text-align:left;
    margin-left: 50px;
  }
 type: 'custom:generic-remote-control-card'`

Also doesn't matter what i put in the config (one of below) I get: Component error: resources - Integration 'resources' not **found.**


`resources:
    type: module 
    url: /config/www/community/generic-remote-control-card/generic-remote-control-card.js

resources:
    url: /hacsfiles/generic-remote-control-card/generic-remote-control-card.js
    type: module`

Can you maybe correct anything you think i've done wrong? Maybe just to add, I'm running the container HA (no supervisor)  version: 20210603.0

Thank you.

**Comment by DennisOtt-git-hub** [comment]
I parsed your code and it appears everything is there.  I add the following to my ui-lovelace.yaml (dropping the button code and just calling the remote_template) just to see if it would display and it rendered the remote image just fine....

  - title: Test Samsung Remote Remote Controls
    visible: true
    path: samsung_remote_control 


    name: Samsung 
    remote_template: samsungtv 
    style: | 
        ha-card { 
          font-size: 10px; 
        } 
        h1{ 
          text-align:left; 
          margin-left: 50px; 
        } 

    type: 'custom:generic-remote-control-card'


I will say that, like most things in HA it was very particular about indention and I have to play with it to get it all right before it would render.  But to me it sounds like you may have a different issue if it is complaining about resources being available.  I have had a couple of custom cards not work in my instance with the same error.  Some eventually correct themselves with restarts, some have never worked.  I assumed it was a compatibility issue with the version I was on but I cannot say for sure.... I just passed on those cards.  I suspect not everything is compatible.  

Unfortunately I am on core-2012.8.7 (with supervisor) and I do everything in yaml code and it sounds like you are using the widgets so I may not be much help.

**Comment by wube1** [comment]
@DennisOtt-git-hub,
Hi Dennis, i got the card to work. I chose from GUI to manually write yaml and pasted my config. Now i have a problem with error message saying:

http://q:8123/hacsfiles/generic-remote-control-card/generic-remote-control-card.js?hacstag=263901624023:103:26 Uncaught TypeError: Cannot read properties of null (reading 'volplus')

when i press any of my mapped buttons. May i ask if you know a solution to this?

**Comment by wube1** [comment]
Hi @dimagoltsman ,
It's been a while and i still can't actually use the remote. I have the remote graphic present on the card and even text color changes from white to red when i hover the cursor over configured buttons. 

So now my question is why it still doesn't work? Maybe i don't understand something here. If this can be used with entity: remote.rm_mini_3_remote and remote.send_command in my opinion it should work. Sample code below:

},
                            "nine": {
                                "call": "remote.send_command",
                                "data": {
                                    "entity_id": "remote.rm_mini_3_remote",
                                    "command": "b64:JgBIAAABIpITEhM3EzcTEhMSExITEhM3ExITNxM3EzcTEhMSExITEhM3ExITEhM3EhMSEhMSExITEhM3EzcTEhM3EzcTNxM3EwANBQ=="
                                }
                            },
                            "exit": {
                                "call": "remote.send_command",
                                "data": {
                                    "entity_id": "remote.rm_mini_3_remote",
                                    "command": "b64:JgCMAI+TEzgRNxI4EhMSEhITExISExI3EjgSNxITEhMSExITEhMROBITETgSNxMSEjgTEhISEhMSOBISExITNxISEzcTNhMABgGSlRI4EjcSNxQRExMRExITEhMROBI3EjgSEhITEhMSFBETETgSExI3EjgSExI3EhQRExITETgSFBETETgTEhI3EjgSAA0FAAAAAAAAAAAAAAAA"
                                }

Can you please give me an advice?

Let me add that i have configured all the buttons i want via:

platform: broadlink
 mac: !secret rm_mini3_mac
 switches:
    - name: "Volume Up"
      command_on:  'JgBQAAABIZMTEhITEhMSExITEhITNxI4EjcTNxI3EjgTNxI3EhMSExM3EhITNxITEjgSEhMSEjcTExI3ExISNxMSEjgTNxISEwAFGgABJ0oSAA0FAAAAAAAAAAA='
      command_off:  'JgBQAAABIZMTEhITEhMSExITEhITNxI4EjcTNxI3EjgTNxI3EhMSExM3EhITNxITEjgSEhMSEjcTExI3ExISNxMSEjgTNxISEwAFGgABJ0oSAA0FAAAAAAAAAAA='
    - name: "Volume Down"
      command_on: 'JgBQAAABIpITEhIUERMUERITEhITNxI4EjcTNxI4EjcTNxM2EhQRExQ2EhIUERITExITEhITEjgRExI4EjcTNxI4EjcTNxMRFAAFGgABJ0kSAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABIpITEhIUERMUERITEhITNxI4EjcTNxI4EjcTNxM2EhQRExQ2EhIUERITExITEhITEjgRExI4EjcTNxI4EjcTNxMRFAAFGgABJ0kSAA0FAAAAAAAAAAA='
    - name: "Woofer Up"
      command_on: 'JgBQAAABIpMTEhITEhMSExITEhITNxI3EzcTNxI3EjgTNxI3EhMSExMSEhMSNxITEjgSExISEzcSNxI4ExISNxMSEjgTNxISEwAFGgABJ0oSAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABIpMTEhITEhMSExITEhITNxI3EzcTNxI3EjgTNxI3EhMSExMSEhMSNxITEjgSExISEzcSNxI4ExISNxMSEjgTNxISEwAFGgABJ0oSAA0FAAAAAAAAAAA=' 

and they are visible as switches in entities.

Thanks in advance for your help.

**Comment by dimagoltsman** [comment]
i cant understand this way what is the exact problem, what is the error? what works? what doesnt? what did u change?

**Comment by wube1** [comment]
Hi @dimagoltsman ,
I followed your exmaple in main page and i have the remote graphic present in my card. I changed the commands for my own of course. As i use Broadlink RM mini3, i changed the entity_id to remote.rm_mini_3_remote. Buttons which i programmed change the color on the remote from white to red when i hover mouse over them but when i click on them my rm mini 3 doesn't send the command. In the logs i get: "http://q:8123/hacsfiles/generic-remote-control-card/generic-remote-control-card.js?hacstag=263901624023:103:26 Uncaught TypeError: Cannot read properties of null (reading 'two')"

**Comment by dimagoltsman** [comment]
ok so follow the logs, you probably missed something creating the new card

**Comment by wube1** [comment]
What screenshots or code/log samples i should post here in order for you to help me out?
1. When installing the card from HACKS there is no configuration - you click install and it's done
2. In the new dashboard i go to edit and raw configuration editor and paste below code mentioned already few times up in the thread, of course b64 commands are my own and they work as scripts in different dashboard. I can see the remote and click on the buttons.
3. In resources.yaml i added:

  - url: /hacsfiles/generic-remote-control-card/generic-remote-control-card.js
    type: module

That's pretty much it

**Comment by dimagoltsman** [comment]
closing as inactive
