### ISSUE TITLE
Aesthetic adjustment to correctly display a samsung remote custom card

### ISSUE THREAD

**Issue by Ninuss** [dimagoltsman/generic-remote-control-card#18]
Hi, I tried looking in the code to find the spot where a layer of the Samsung remote controls is displayed shifted by a large amount of pixels to the right in the Home Assistant dashboard. I have not succeeded. I attach some screenshots to immediately understand the imperfection, circled in red I highlight the card and the horizontal navigation bar. Everything is perfectly functional anyway, but, if I can also be a little more precise, the lower part of the photo of the remote control would be missing, but that's not a problem, just a simple detail. Thanks in advance for your reply.

![Desktop Screenshot 2021 09 17 - 10 55 51 78_LI](https://user-images.githubusercontent.com/23480313/133756378-ea684c4d-1df1-4dde-98a2-4cd6f021270d.jpg)

![Desktop Screenshot 2021 09 17 - 10 56 07 61_LI (2)](https://user-images.githubusercontent.com/23480313/133756404-6de86408-fc4e-4ae2-94dc-1eb36e7f6d26.jpg)

**Comment by dimagoltsman** [comment]
closing as inactive

**Comment by FrancYescO** [comment]
i still have this bug

**Comment by si458** [comment]
I have the same problem here but with the apple tv 4k remote?
It renders the image on the left but then you scroll all the way to the right and you find random text string for each button?

**Comment by callmemitch27** [comment]
I have this same problem with the LG_new remote - tried implementing the fix used here for the samsung remote but it did not work
