### ISSUE TITLE
Changing remote-html.js and the result is not showed

### ISSUE THREAD

**Issue by FlyProg** [dimagoltsman/generic-remote-control-card#23]
Hello,

When I change the icons positions on remote-html.js I will see the card and I don't see the changes.
How can we refresh the changes to be visible on the card?

Thank you and congratulations for the great job.

**Comment by dimagoltsman** [comment]
HA creates a cach, you should delete it, its in the addon folder

**Comment by mauroluis-poa** [comment]
please. i am user docker container. do you know where is this folder?
