### ISSUE TITLE
How do I send you my work? Apple Fire TV remote and Amazon Firestick remote

### ISSUE THREAD

**Issue by richsimpson** [dimagoltsman/generic-remote-control-card#24]
I have used your info to produce two remotes and happy to share with you. I don;t know how though!

I have remote for 4k Apple TV and 4k Amazon Firestick
![apple4kremote](https://user-images.githubusercontent.com/51749826/173572465-14b67ab9-8c67-42d5-93b0-624c48b85e4f.png)
![firestick4kremote](https://user-images.githubusercontent.com/51749826/173572471-3bdde935-b560-418a-b836-c55f48374556.png)

I have the remote-html file and all the separate images for buttons but I don;t think you expect me to just add them all to this message. 

Sorry not done this before but happy to share my work.

**Comment by richsimpson** [comment]
I think I have worked it out. I have done something to make a version (forked?) and hopefully you see it and can take the work in that way?

**Comment by dimagoltsman** [comment]
just fork my project and create a pull request, ill see it and merge

**Comment by richsimpson** [comment]
I think I have done all that, cheers
