### ISSUE TITLE
New Feature Request: Harmony Hub Support

### ISSUE THREAD

**Issue by interaction-designer** [dimagoltsman/generic-remote-control-card#5]
Your remotes look very nice!
Can you please consider adding support for the Harmony Hub too?
This would make your remote truly "Generic". 
Thanks!

**Comment by Dinth** [comment]
I believe this remote is for sending IR codes, not controlling Harmony integration. Please check "Harmony Card" frontend addon, it works great for me with Harmony.

**Comment by dimagoltsman** [comment]
it is truly generic. it supports any entity, take a look at Mibox Remote example, you specify entity id and data.
this way it can be used for any entity in the system
